---
downloads: ~/.ansible-downloads/

timezone: Europe/Amsterdam

configure_dotfiles: true
configure_osx: true

dotfiles_repo: git@github.com:skanct/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/Development/github.com/dotfiles

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - gpg
  - httpie
  - sqlite
  - mcrypt
  - nmap
  - ssh-copy-id
  - readline
  - openssl
  - wget
  - nvim
  - mas
  - htop
  - bat
  - exa
  - jq
  - awscli
  - { name: mosh, install_options: HEAD }
  - tmux
  - gh
  - git-delta
  - fd
  - ripgrep
  - mcfly
  - pinentry-mac
  - fzf
  - stow
  - zoxide
  - node
  - yarn
  - libxmlsec1

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - brave-browser
  - handbrake
  - licecap
  - slack
  - visual-studio-code
  - alfred
  - mailmate
  - zoom
  - microsoft-teams
  - little-snitch
  - keybase
  - kitty
  - skype
  - font-jetbrains-mono-nerd-font
  - screenflow
  - webex-meetings
  - fantastical
  - macfuse

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1333542190, name: "1Password 7 - Password Manager" }
  - { id: 1317704208, name: "eduVPN client"}
  - { id: 462054704, name: "Microsoft Word"}
  - { id: 985367838, name: "Microsoft Outlook"}
  - { id: 462058435, name: "Microsoft Excel"}
  - { id: 462062816, name: "Microsoft PowerPoint"}
  - { id: 1274495053, name: "Microsoft To Do "}
  - { id: 823766827, name: "OneDrive"}
  - { id: 1091189122, name: "Bear – Markdown Notes"}
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - name: ipython
    state: present
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

install_nvim_plugins: true

install_vscode_extensions: true
vscode_extensions:
  - ms-python.ms-python
  - samuelcolvin.jinjahtml
  - ms-vscode-remote.remote-ssh
  - yzhang.markdown-all-in-one

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
