---
downloads: ~/.ansible-downloads/

timezone: Europe/Amsterdam

configure_dotfiles: true
configure_terminal: true
configure_osx: true
configure_dock: false
dockitems_remove: []
dockitems_persist: []
configure_sudoers: false
sudoers_custom_config: ''


dotfiles_repo: git@github.com:skanct/dotfiles.git
dotfiles_repo_accept_hostkey: True
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/Development/github.com/dotfiles

homebrew_installed_packages:
  - git
  - lazygit
  - gpg
  - go
  - httpie
  - sqlite
  - nmap
  - ssh-copy-id
  - readline
  - openssl
  - wget
  - nvim
  - mas
  - htop
  - eza
  - bat
  - jq
  - awscli
  - { name: mosh, install_options: HEAD }
  - tmux
  - zellij
  - starship
  - gh
  - git-delta
  - fd
  - ripgrep
  - mcfly
  - pinentry-mac
  - fzf
  - stow
  - zoxide
  - node
  - yarn
  - libxmlsec1
  - pdm
  - uv
  - ruff
  - helix
  - atuin
  - mdformat
  - marksman

homebrew_taps:
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - macfuse
  - wezterm
  - font-jetbrains-mono-nerd-font
  - font-fira-code-nerd-font
  - visual-studio-code
  - brave-browser
  - firefox
  - orion
  - mailmate
  - fantastical
  - signal
  - slack
  - zoom
  - webex-meetings
  - alfred
  - handbrake
  - licecap
  - screenflow
  - podman-desktop
  - nikitabobko/tap/aeropspace
  - felixkratz/formulae/borders
  - font-sf-pro
  - bruno
  - ghostty

mas_installed_apps:
  - {id: 1317704208, name: "eduVPN client"}
  - {id: 462054704, name: "Microsoft Word"}
  - {id: 985367838, name: "Microsoft Outlook"}
  - {id: 462058435, name: "Microsoft Excel"}
  - {id: 462062816, name: "Microsoft PowerPoint"}
  - {id: 823766827, name: "OneDrive" }
  - {id: 1091189122, name: "Bear – Markdown Notes"}
  - {id: 1352778147, name: "Bitwarden"}
  - {id: 1451685025, name: "WireGuard"}
  - {id: 585829637, name: "Todoist"}
mas_email: ""
mas_password: ""

# Installed by stow
osx_script: "~/.osx --no-restart"

install_nvim_plugins: True

install_vscode_extensions: True
vscode_extensions:
  - ms-python.ms-python
  - samuelcolvin.jinjahtml
  - ms-vscode-remote.remote-ssh
  - yzhang.markdown-all-in-one

post_provision_tasks: []
